### PR TITLE
Chore/setup repo

### PR DESCRIPTION
**Pull request by efficient0482**
With this PR we move the ECO-Pass KIT Documentation to the dedicated Tractus-X Repository.

ToDos:
- [x] add Code of Conduct File
- [x] add License file
- [x] add security file
- [x] add contributing file
- [x] add Notice file
- [x] add Dependency files
- [x] add CC-BY-4.0 License
- [x] add CC-BY Template to documentation files
- [x] add CC-BY Template files for resources
- [x] fill copyright owner

### CODE REVIEW

**Comment by efficient0482** [comment]
@matbmoser @AngelikaWittek please review,should be now compliant

**Comment by matbmoser** [comment]
I reviewed the changes from a TRG compliance for me its ok, just would like to get the approval from @AngelikaWittek if you can be so kind.

Now from a content perpective, for a initial version is ok for me however there are some things I would change:

Please update this diagram in next versions: https://github.com/LuisRickert/eco-pass-kit-fork/blob/chore/setup-repo/docs/resources/development-view/adoption-view-EcoPassKIT_IT_Arch.png -> Check the new Arc42: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/arc42/ContextDiagram.jpeg

Now the new architecture includes BPN Discovery, EDC Disocvery etc

Some images are also in not good size they are too litle to visualize in github:
- https://github.com/LuisRickert/eco-pass-kit-fork/blob/chore/setup-repo/docs/resources/adoption-view/adoption-view-EcoPassKITBusinessArch.svg
- https://github.com/LuisRickert/eco-pass-kit-fork/blob/chore/setup-repo/docs/resources/adoption-view/adoption-view-BatteryPass_a_example.svg

**Comment by efficient0482** [comment]
> 

Thanks for your review, I'll get the updates.

**Comment by matbmoser** [comment]
Hi @LuisRickert, 

Please solve the conflicts here 
image


Then I can merge it.

**Review by matbmoser — CHANGES_REQUESTED** [review]
This is my final review about the trgs for kits, documentation and legal stuff.

What is done: 

- [x]  All the legal requirements from TRGs 7.05, 7.07, 7.08 that were missing are now included
- [x]  The necessary legal documentation and repo structure was added


What is still missing in my perspective:
- Please add a basic readme with description for the eco pass KIT. With the logo if possible and the name of the repository (in a human readable way) Eco Pass Kit or Eco Pass KIT (https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) (Installation guide is not needed)
- Keep the change log in the root path from the repo (not in docs folder) https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3. 
     -  Rename it to CHANGELOG.md, 
     -  Follow the structure defined here: https://keepachangelog.com/en/1.0.0/
     - If you need an example here it is: https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md
- Add in the root path a `.tractusx` file with the following content: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5 (You can use ours as an example: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/.tractusx
- You dont need the `DEPENDENCIES` file, I would remove it, is just for code repos or if you use a specific library to generate the docs.

**Comment by matbmoser** [comment]
First of all, thank you for the awesome Job! 💯 🥇 🎉 

I revised in deep the TRGs to see if you forgot something.

@LuisRickert because is the first contribution there is some things that are still missing.

However just add/fix this little things and I can approve the PR. Please just note that I am having conflicts to merge the files please resolve them also so that I can merge it. Otherwise I will need to solve them by my self in your fork...

**Comment by efficient0482** [comment]
**formal requirements:**
- [x] add basic readme as specified [here](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1) Installation Guide can be omitted
- [x] move changelog to root directory of the repository
- [x] rename changelog file to CHANGELOG.md 
- [x] keep the following structure in the change log [here](https://keepachangelog.com/en/1.0.0/) [Example](https://github.com/eclipse-tractusx/tractus-x-release/blob/main/CHANGELOG.md)
- [x] create directory in root `.tractucsx` with [this](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5)
- [x] remove `dependency` file
- [x] resolve merge conflict

**content review:**
- [x] pictures to small
- [x] update [this](https://github.com/LuisRickert/eco-pass-kit-fork/blob/chore/setup-repo/docs/resources/development-view/adoption-view-EcoPassKIT_IT_Arch.png) diagramm according to [this] (https://github.com/eclipse-tractusx/digital-product-pass/blob/main/docs/arc42/ContextDiagram.jpeg)

edit: 
typo

**Comment by efficient0482** [comment]
@matbmoser finally  😄 done ✅

**Review by matbmoser — APPROVED** [review]
Ok now I can approve the changes. All them is documentation and has the correct licenses. After my detailed review the documentation is compliant to the TRGs. Now we are ready to merge this.

**Pull request merged**
